name: Deploy to Render

on:
  push:
    paths:
      - 'PROG3176_Assignment2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"

    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
